name: CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install client dependencies
      run: cd client && npm ci

    - name: Run server linting
      run: npm run lint

    - name: Run client linting
      run: cd client && npm run lint

    - name: Run backend tests
      run: npm test

    - name: Run frontend tests
      run: npm run test:frontend

    - name: Build client
      run: npm run build

    - name: Generate test coverage
      run: npm run test:coverage